config/routes.rb
Rails.application.routes.draw do

  # config/routes.rb
  mount ActionCable.server => '/cable'

  resources :contacts
  get 'admin' => 'admin#index'



  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end



  resources :products do
    get '/likes', to: 'c#a'
    collection do
      get '/likes_collection', to: 'c#a'
      get :my # => /products/my
    end
    member do
      get :details
    end

    resources :comments
    resources :images
  end


  resources :products do
    get :who_bought, on: :member
  end


  scope "/:locale" do
    resources :orders
  end

  resource  :products
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  root 'home#index', as: 'home_index', via: :all




end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
   
  enum pay_type: {
      "Check"              => 0,
      "Credit card"        => 1,
      "Purchase order"     => 2 
  }

  validates :name, :address, :e_mail, presence: true
  validates :pay_type, inclusion: pay_types.keys   


  def add_line_items_from_cart (cart)
    cart.line_items.each do |item|
     item.cart_id = nil
       line_items << item
   end
  end

  def total_price
    line_items.to_a.sum{|item| item.total_price}
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  skip_before_action :authorize, only: [:new, :create]
  before_action :set_cart, only: [:new, :create]
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderMailer.received(@order).deliver_later
        OrderMailer.shipped(@order).deliver_later
        format.html { redirect_to products_url, notice:
          I18n.t('thanks') }
          format.js { redirect_top roducts_url, alert:
          'Thank you for you order.' }

        format.json { render :show, status: :created,
           location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def ensure_cart_isnt_empty
    if @cart.line_items.empty?
      redirect_to products_url, notice: 'Your cart is empty'
    end  
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :pay_type, :e_mail)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%=raw t('errors.template.header', count: @order.errors.count,
                   model: t('activerecord.models.order')) %></h2>
      <p><%= t('errors.template.body') %></p>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= raw message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, t('order.form.name') %>
    <%= f.text_field :name, size: 40, :class=>"form-control",
                     :id=>"exampleInputPassword1", :placeholder=>"Name" %>
  </div>

  <div class="form-group">
    <%= f.label :address, t('order.form.address_html')%>
    <%= f.text_area :address, rows: 3, cols: 40, :class=>"form-control",
        :id=>"exampleFormControlTextarea1"  %>
  </div>

  <div class="form-group">
    <%= f.label :e_mail, t('order.form.email')%>
    <%= f.email_field :e_mail, size: 40, :class=>"form-control", :id=>"exampleFormControlInput1",
                      :placeholder=>"name@example.com" %>
  </div>

  <div class="form-group">
    <%= f.label :pay_type, t('order.form.pay_type')%>
    <%= f.select :pay_type, Order.pay_types.keys,
                                     prompt: t('order.new.Select_a_payment_method'),
                 :class=>"form-control", :id=>"exampleFormControlSelect1" %>
  </div>



  <div class="col-auto">
    <%= f.submit t('order.form.submit'), :class=>"btn btn-primary mb-2"%>
  </div>
<% end %>

app/views/orders/_total_price.erb
<%=t('cart.Total_price')%> <b> <%= number_to_currency(@cart.total_price) %></b>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Pay type</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.pay_type %></td>
        <td><%= order.e_mail %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="container">
  <div class="card shopping-cart">
    <div class="card-header bg-dark text-light">
      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
      <%=t('cart.title') %>
      <%= link_to t('cart.continiu_shopping'), products_path, :class =>"btn btn-outline-info btn-sm pull-right" %>
      <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <div id="line_items">
      <%= render(@cart.line_items) %>
      </div>

    </div>
    <div class="card-footer">
      <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
        <div class="row">

          <div class="col-6">
            <%= button_to t('cart.empty'), @cart, method: :delete, :class=>"btn btn-danger",
                          data: {confirm: 'Are you sure?'}%>
          </div>
        </div>
      </div>
      <div class="pull-right" style="margin: 10px">
        <div class="pull-right" style="margin: 5px">
          <div id="total_price">
         <%= render partial: 'orders/total_price' %>
          </div>
        </div>

        <div id="total_price">

        </div>
      </div>
    </div>
  </div>
</div>


  <fieldset>
    <h2 id="order_legend"><%= t('order.new.legend') %></h2>
    <%= render 'form', order: @order %>
  </fieldset>

app/views/orders/new.js.erb
$alert('hello');
$('#check').hide();
$('#check').css({'background-color':'#b9cae5'})

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong> pay type:</strong>
  <%= @order.pay_type %>
</p>

<p>
  <strong> email:</strong>
  <%= @order.e_mail %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>