config/routes.rb
Rails.application.routes.draw do

  # config/routes.rb
  mount ActionCable.server => '/cable'

  resources :contacts
  get 'admin' => 'admin#index'



  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end



  resources :products do
    get '/likes', to: 'c#a'
    collection do
      get '/likes_collection', to: 'c#a'
      get :my # => /products/my
    end
    member do
      get :details
    end

    resources :comments
    resources :images
  end


  resources :products do
    get :who_bought, on: :member
  end


  scope "/:locale" do
    resources :orders
  end

  resource  :products
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  root 'home#index', as: 'home_index', via: :all




end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments,
           source: :user
  has_many :uniq_commented_users, -> { uniq },
           through: :comments,
           source: :user
  has_many :line_items         
  has_many :orders, through: :line_items



  has_many :images, as: :imagable, inverse_of: :imagable

  accepts_nested_attributes_for :images, allow_destroy: true

  # before_destroy :ensure_not_referenced_by_any_line_item

  validates :price, :description, :name, presence: true
  validates_uniqueness_of :name

  before_validation do
    puts 'before_validation'
  end
  before_save do
    puts 'before_save'
  end
  before_create do
    puts 'before_create'
  end
  before_update do
    puts 'before_update'
  end
  before_commit do
    puts 'before_commit'
  end

  after_validation do
    puts 'after_validation'
  end
  after_save do
    puts 'after_save'
  end
  after_create do
    puts 'after_create'
  end
  after_update do
    puts 'after_update'
  end
  after_commit do
    puts 'after_commit'
  end


end

private

def ensure_not_referenced_by_any_line_item
  unless line_items.empty?
    error.add(:base, 'Line Items present')
    throw :abort
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #skip_before_action :before_some_method, except: [:index]
  # skip_before_action  :authenticate_user!

  skip_before_action :authorize

  def index


    @page = params[:page].present? ? params[:page].to_i : 1

    @products = if params[:Product_name]
                  Product.page(@page).where('name LIKE ?', "%#{params[:Product_name]}%")
                else
                  Product.page(@page)
                end
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def update
    # @product.update(product_params)
    # redirect_to @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { 
          redirect_to @product,
        notice: 'Product was successfully updated.' }
      format.json { render :show, status: :ok, location: @product }
     
      @products = Product.all
      ActionCable.server.broadcast 'products',
      html: render_to_string('products/index', layout: false)

      @carts = Cart.all
      ActionCable.server.broadcast 'carts',
      html: render_to_string('carts/show', layout: false)

      else
        format.html { render :edit }
      format.json { 
        render json: @product.errors,
      status: :unprocessable_entity }
      end
    end
  end

  def create
    Product.create(product_params)

    redirect_to products_path
    
  end

  def destroy
    @product.destroy

    if request.xhr?
      head :no_content
    else
      redirect_to products_path
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end


  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, images_attributes: [:id,:file,:_destroy])
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def price_format(value)
    "#{value} $"
  end

end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%=f.text_field :name,  placeholder:  'name'%>
  <%=f.text_field :price, placeholder: 'price' %>
  <br>
  <br>
  <%= f.text_area :description, rows:2 , cols: 60%>

  <%=f.fields_for :images do |img_f|%>
    <%= render 'image_fields', f: img_f %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'add image', f, :images %>
  </div>
  <%=f.submit 'Create' %>
<% end %>

app/views/products/_image_fields.html.erb
<div class = "nested-fields">
  <%= f.file_field :file %>
  <%= f.hidden_field :_destroy, class: '_destroy' %>
  <br>
  <%= image_tag(f.object.file_url, width: '100') if f.object.file.present? %>
<!--  <a href="#" class="remove-image">remove image</a>-->
  <%= link_to_remove_association 'remove img', f %>
</div>

app/views/products/edit.html.erb
<%= render partial: 'products/form' %>

app/views/products/index.html.erb
<div class="row">
<% @products.each do |product| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
         <!-- <%#=image_tag product.images[0].file_url, :class=> "card-img-top" %>-->

          <%=link_to((image_tag product.images[0].file_url, :class=> "card-img-top"),product_path(id: product.id))%>

          <div class="card-body">
            <div class="prod_name">
              <%= link_to product.name, product_path(id: product.id)%>
            </div>
            <p class="card-text"> <%= truncate(strip_tags(product.description), length: 200) %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= button_to t('products.add_cart_html'),line_items_path(product_id: product), remote: true,
                              class: 'btn btn-sm btn-outline-secondary'%>
              <!--
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              -->
                <%= link_to t('products.comments'), product_comments_path(product),
                            class: 'btn btn-sm btn-outline-secondary' %>
              </div>
              <small class="text-muted">9 mins</small>
              <small style="color: #B00100"> <%= t('products.price') + price_format(product.price) %></small>

            </div>
          </div>
        </div>
      </div>
<% end %>
</div>

<%= paginate @products,
             :pagination_class => "pagination"%>


<!--
<div class="create_prod">
<%#= link_to  'Create New Product', new_product_path %>
</div>
-->

app/views/products/new.html.erb
form input

<%= form_for @product do |f| %>
<%=f.text_field :price, placeholder: 'price' %>
<%=f.text_field :name,  placeholder:  'name'%>
<%=f.submit 'Create' %>
<% end %>

app/views/products/show.html.erb
<br><br><br><br><br>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">

    <ol class="carousel-indicators">
      <%@product.images.each_with_index do |image, index| %>
        <% next unless image.file_url %>
        <% if index == 0 %>
          <li data-target="#carouselExampleIndicators" data-slide-to=<%=index%> class="active"></li>
        <% else %>
          <li data-target="#carouselExampleIndicators" data-slide-to=<%=index%>></li>
        <% end %>

      <% end %>
    </ol>

    <%@product.images.each_with_index do |image, index| %>
      <% next unless image.file_url %>
      <% if index == 0 %>
        <div class="carousel-item active">
      <% else %>
        <div class="carousel-item">
      <% end %>
      <%= image_tag(image.file_url, class: "d-block w-100") %>

      <div class="carousel-caption d-none d-md-block">

        <h5 style="color: crimson"><%=@product.name%></h5>
        <h3 style="color: #cc0000"><%= t('products.price') + price_format(@product.price) %></h3>
      </div>

      </div>
    <% end %>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br><br><br><br>
  <%= button_to t('products.add_cart_html'),line_items_path(product_id: @product), method: :post, remote: true,
                class: 'btn btn-primary'%>
  <br><br><br>

  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="#"><%=t('products.description')%></a>
        </li>
        <li class="nav-item">
          <%= link_to t('products.comments'), product_comments_path(@product), :class => "nav-link" %>
        </li>

      </ul>
    </div>
    <div class="card-body">
      <%= @product.description%>
    </div>
  </div>


</div>




<%#= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %>
<%#= link_to 'Show comments', product_comments_path(@product) %>