config/routes.rb
Rails.application.routes.draw do

  # config/routes.rb
  mount ActionCable.server => '/cable'

  resources :contacts
  get 'admin' => 'admin#index'



  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end



  resources :products do
    get '/likes', to: 'c#a'
    collection do
      get '/likes_collection', to: 'c#a'
      get :my # => /products/my
    end
    member do
      get :details
    end

    resources :comments
    resources :images
  end


  resources :products do
    get :who_bought, on: :member
  end


  scope "/:locale" do
    resources :orders
  end

  resource  :products
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  root 'home#index', as: 'home_index', via: :all




end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart


  def total_price
    product.price * quantity
  end


end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  include CurrentCart
  skip_before_action :authorize, only: [:create, :destroy]
  before_action :set_cart, only: [:create, :destroy]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show

  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  def remove_item

    product = Product.find(params[:product_id])
    @line_item = @cart.remove_product(product)

    respond_to do |format|
      if @line_item.save
        format.html {redirect_to @line_item.cart}
        format.json {render :show, status: :created, location: @line_item}
      else
        format.html {render :new}
        format.json {render json: @line_item.errors, status: :unprocessable_entity}
      end
    end

  end

  # POST /line_items
  # POST /line_items.json
  def create

    product = Product.find(params[:product_id])

    if params[:remove] then
      @line_item = @cart.remove_product(product)
    elsif params[:delete] then
      @line_item = @cart.delete_product(product)
    else
      @line_item = @cart.add_product(product)
    end

    respond_to do |format|
      if @line_item.save
        #format.html {redirect_to new_orders_url}
        #format.html { redirect_to products_url }
        format.js
        format.json {render :show,
                            status: :created, location: @line_item}
      else
        format.html {render :new}
        format.json {render json: @line_item.errors, status: :unprocessable_entity}
      end
    end
    update_cart_show
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html {redirect_to @line_item, notice: 'Line item was successfully updated.'}
        format.json {render :show, status: :ok, location: @line_item}

      else
        format.html {render :edit}
        format.json {render json: @line_item.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      if @line_item.destroy
        format.html {redirect_to line_item_url}
        # format.html { redirect_to @line_item.cart}
        format.js
        format.json {render :show, status: :created, location: @line_item}
      else
        format.html {render :new}
        format.json {render json: @line_item.errors, status: :unprocessable_entity}
      end
    end
    update_cart_show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def line_item_params
    params.require(:line_item).permit(:product_id)
  end

  def update_cart_show

    begin
      @carts = Cart.all
      ActionCable.server.broadcast 'carts', html: render_to_string(partial: @cart, layout: false)
    end

  end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
  <!-- PRODUCT -->
<div class="row">
  <div class="col-12 col-sm-12 col-md-2 text-center"><!--
    <%#=image_tag line_item.product.images[0].file_url, :class=> "img-responsive", :alt=>"prewiew", :width=>"120", :height=>"80"%>
  -->

    <%= link_to((image_tag line_item.product.images[0].file_url, :class=> "img-responsive", :alt=>"prewiew", :width=>"120", :height=>"80") ,
                product_path(id: line_item.product.id))%>
  </div>
  <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
    <div class="prod_name">
      <%= link_to line_item.product.name, product_path(id: line_item.product.id)%>
    </div>
    <h4>
      <small><%=line_item.product.description%></small>
    </h4>
  </div>
  <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
    <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
      <h6><strong><%= number_to_currency(line_item.product.price)%><span class="text-muted">x</span></strong></h6>
    </div>
    <div class="col-2 col-sm-2 col-md-2">
      <div class="quantity">
        <%= line_item.quantity %>
      </div>
    </div>
    <%= button_to '+', line_items_path(product_id: line_item.product), :class=>"plus", remote: true %>
    <%= button_to '-', line_items_path(product_id: line_item.product, remove:true), :class=> "minus", remote: true %>
    <div class="col-2 col-sm-2 col-md-2 text-right">

        <%= button_to t('line_items.delete'), line_item_path(line_item.id), method: :delete,
                      :class=>"btn btn-primary btn-sm", remote: true %>
      </button>

    </div>
  </div>
</div>
<hr>
<!-- END PRODUCT -->

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
            line_item.quantity,
            truncate(line_item.product.name, length: 50)) %>

app/views/line_items/create.js.erb
/*$('#new_order').hide();

if ($('#cart tr').length == 1) {$('#cart').show('blind', 1000);}*/


$ ('#cart').html("<%=j render(@cart)%>");

if ($('#line_items').length > 0) {$('#line_items').html("<%=j render(@cart.line_items) %>")};
if ($('#total_price').length > 0) {$('#total_price').html("<%=j render('orders/total_price') %>")};

app/views/line_items/destroy.js.erb
$('#cart').html("<%=j render(@cart)%>");
$('#line_items').html("<%=j render(@cart.line_items) %>");
$('#total_price').html("<%=j render('orders/total_price') %>");

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>