config/routes.rb
Rails.application.routes.draw do

  # config/routes.rb
  mount ActionCable.server => '/cable'

  resources :contacts
  get 'admin' => 'admin#index'



  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end



  resources :products do
    get '/likes', to: 'c#a'
    collection do
      get '/likes_collection', to: 'c#a'
      get :my # => /products/my
    end
    member do
      get :details
    end

    resources :comments
    resources :images
  end


  resources :products do
    get :who_bought, on: :member
  end


  scope "/:locale" do
    resources :orders
  end

  resource  :products
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  root 'home#index', as: 'home_index', via: :all




end

app/models/cart.rb
class Cart < ApplicationRecord

 has_many :line_items, dependent: :destroy
 # has_one  :bin, dependent:  :destroy

 def add_product(product)

 current_item = line_items.find_by(product_id: product.id)

 if current_item
  current_item.quantity += 1
 else
  current_item = line_items.build(product_id: product.id)
 end
 current_item

 end

 def remove_product(product)

 current_item = line_items.find_by(product_id: product.id)

 if current_item and current_item.quantity != 1
        current_item.quantity -= 1
       
 end

 current_item

end

def delete_product(product)

  current_item = line_items.find_by(product_id: product.id)
  current_item.delete
  
  current_item

end



 def total_price
   line_items.to_a.sum{|item| item.total_price}
 end

  def total_qty
    line_items.to_a.sum{|item| item.quantity}
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  #delegate :full_name, to: :user, prefix: true

  validates :text, :product, presence: true
  validates :text, length: { maximum: 140 }

   after_commit :notify!

  def as_json(_ = nil)
    {
        id: id,
        product_id: product_id,
        user_id: user_id,
        text: text,
        nick: user || 'Guest'
    }
  end

  private

  def notify!
    action = if self.persisted?
               'comments.new'
             else
               'comments.destroy'
             end
    Pusher.trigger('broadcast', action, self.as_json)
    # WsQueue.publish(action, self)
  end
end

app/models/comment_observer.rb
class CommentObserver < ActiveRecord::Observer
  def after_commit(comment)
    action = if comment.persisted?
               'comments.new'
             else
               'comments.destroy'
             end
    # binding.pry
    CommentJob.perform_later(action, comment.as_json)
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imagable, polymorphic: true, inverse_of: :imagable
  mount_uploader :file, ImageUploader
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart


  def total_price
    product.price * quantity
  end


end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
   
  enum pay_type: {
      "Check"              => 0,
      "Credit card"        => 1,
      "Purchase order"     => 2 
  }

  validates :name, :address, :e_mail, presence: true
  validates :pay_type, inclusion: pay_types.keys   


  def add_line_items_from_cart (cart)
    cart.line_items.each do |item|
     item.cart_id = nil
       line_items << item
   end
  end

  def total_price
    line_items.to_a.sum{|item| item.total_price}
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments,
           source: :user
  has_many :uniq_commented_users, -> { uniq },
           through: :comments,
           source: :user
  has_many :line_items         
  has_many :orders, through: :line_items



  has_many :images, as: :imagable, inverse_of: :imagable

  accepts_nested_attributes_for :images, allow_destroy: true

  # before_destroy :ensure_not_referenced_by_any_line_item

  validates :price, :description, :name, presence: true
  validates_uniqueness_of :name

  before_validation do
    puts 'before_validation'
  end
  before_save do
    puts 'before_save'
  end
  before_create do
    puts 'before_create'
  end
  before_update do
    puts 'before_update'
  end
  before_commit do
    puts 'before_commit'
  end

  after_validation do
    puts 'after_validation'
  end
  after_save do
    puts 'after_save'
  end
  after_create do
    puts 'after_create'
  end
  after_update do
    puts 'after_update'
  end
  after_commit do
    puts 'after_commit'
  end


end

private

def ensure_not_referenced_by_any_line_item
  unless line_items.empty?
    error.add(:base, 'Line Items present')
    throw :abort
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_destroy :ensure_an_admin_remains
  validates :name, presence: true, uniqueness: true
  has_secure_password

  class Error < StandardError

  end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def price_format(value)
    "#{value} $"
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1><%=t('admin.index.welcome')%></h1>
<!--
It's <%#=Time.now %>
We have <%#= pluralize(@total_order, "order")%>.-->

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

  <div id="_navbar-brand">
    <a class="navbar-brand" href="">Electronic<span class="blueColor"> Shop</span></a>
  </div>

  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="navbarCollapse" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to t('layouts.home'), home_index_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" <%= link_to t('layouts.products'), products_path %> </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= t('layouts.qurstions')%> </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= t('layouts.news')%></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" <%= link_to t('layouts.contucts'),contacts_path %> </a>
      </li>
    </ul>
    <% if logged_in? %>
      <li class="nav-item active">
        <a class="nav-link" href="#" style="color: white">   <%=t('layouts.sing')%> <%=current_user.name %> </a>
      </li>
    <%end%>


    <div class="_cart_position">
      <div>
        <%= link_to image_tag('cart.png', size: 7*7),
                    new_order_path, method: :get %>
      </div>


      <div id = "cart">
        <%if  @cart %>
          <div class="cart_cable">
            <%= render @cart %>
          </div>
        <%end %>
      </div>


    </div>
  </div>

  <!--  <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder=<%#= t('layouts.search') %> aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%#= t('layouts.search') %></button>
      </form>-->

  <%= form_tag(products_path, method: :get, class: 'form-inline mt-2 mt-md-0') do %>
    <%= text_field_tag :Product_name, nil, placeholder: t('layouts.search'), class: 'form-control mr-sm-2' %>
    <%= submit_tag t('layouts.search'), name: nil, class:'btn btn-outline-success my-2 my-sm-0' %>
  <% end %>


  <p id="locale">
    <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
    |
    <%= link_to_unless I18n.locale == :ru, "Русский", locale: :ru %>
  </p>


</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>


  <!-- Required meta tags -->
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



  <!--Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->-->

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">





  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



</head>



<body>



<header>
  <div align="alight">







  </div>

  <%= render partial: 'layouts/menu'%>
</header>



<div class="container">

  <%= yield %>

</div>


<!-- Footer -->
<footer class="page-footer">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">



    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
        <p>Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <hr>

  <!-- Call to action -->
  <ul class="list-unstyled list-inline text-center py-2">

    <li class="list-inline-item">

      <% if logged_in? %>
        <%= button_to t('layouts.singout'), logout_path, method: :delete, class:'btn btn-danger btn-rounded' %>
      <% else %>
      <li class="list-inline-item">
        <h5 class="mb-1">Register for free</h5>
      </li>
      <%= link_to t('layouts.singup'), new_user_path, name: nil, class:'btn btn-danger btn-rounded' %>
      <%= link_to t('layouts.singin'), login_path, name: nil, class:'btn btn-danger btn-rounded' %>
    <% end %>

    </li>
  </ul>
  <!-- Call to action -->

  <hr>

  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fa fa-facebook"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fa fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fa fa-google-plus"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fa fa-linkedin"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-dribbble mx-1">
        <i class="fa fa-dribbble"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->





<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/c560c025cf.js"></script>
<!--<script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
    $('carts_cable').popover('update');
</script>-->

<%= action_cable_meta_tag %>

</body>
</html>